name: pyatom
channels:
  - defaults
  - conda-forge
  - nvidia
  - rapidsai
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - absl-py=2.1.0=pyhd8ed1ab_0
  - alembic=1.13.2=pyhd8ed1ab_0
  - alsa-lib=1.2.14=hb9d3cd8_0
  - anyio=4.9.0=pyh29332c3_0
  - argon2-cffi=25.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py311h9ecbd09_5
  - arrow=1.3.0=pyhd8ed1ab_1
  - asttokens=3.0.0=pyhd8ed1ab_1
  - async-lru=2.0.5=pyh29332c3_0
  - attrs=25.3.0=pyh71513ae_0
  - aws-c-auth=0.9.0=h0fbd49f_19
  - aws-c-cal=0.9.2=he7b75e1_1
  - aws-c-common=0.12.4=hb03c661_0
  - aws-c-compression=0.3.1=h92c474e_6
  - aws-c-event-stream=0.5.5=h149bd38_3
  - aws-c-http=0.10.4=h37a7233_0
  - aws-c-io=0.21.2=h6252d9a_1
  - aws-c-mqtt=0.13.3=h19deb91_3
  - aws-c-s3=0.8.6=h800fcd2_2
  - aws-c-sdkutils=0.2.4=h92c474e_1
  - aws-checksums=0.2.7=h92c474e_2
  - aws-crt-cpp=0.33.1=hb4fd278_2
  - aws-sdk-cpp=1.11.606=h31ade35_1
  - azure-core-cpp=1.16.0=h3a458e0_0
  - azure-identity-cpp=1.12.0=ha729027_0
  - azure-storage-blobs-cpp=12.14.0=hb1c9500_1
  - azure-storage-common-cpp=12.10.0=hebae86a_2
  - azure-storage-files-datalake-cpp=12.12.0=h8b27e44_3
  - babel=2.17.0=pyhd8ed1ab_0
  - beautifulsoup4=4.13.4=pyha770c72_0
  - bleach=6.2.0=pyh29332c3_4
  - bleach-with-css=6.2.0=h82add2a_4
  - brotli=1.1.0=hd590300_1
  - brotli-bin=1.1.0=hd590300_1
  - brotli-python=1.1.0=py311hb755f60_1
  - bzip2=1.0.8=hd590300_5
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.9.9=h06a4308_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.18.4=h3394656_0
  - certifi=2025.8.3=py311h06a4308_0
  - cffi=1.16.0=py311hb3a22ac_0
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - colorlog=6.8.2=py311h38be061_0
  - comm=0.2.2=pyhd8ed1ab_1
  - contourpy=1.3.2=py311hd18a35c_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - cyrus-sasl=2.1.28=hd9c7081_0
  - dbus=1.13.6=h5008d03_3
  - debugpy=1.8.14=py311hfdbb021_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - double-conversion=3.3.1=h5888daf_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.0=pyhd8ed1ab_0
  - expat=2.7.1=hecca717_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.58.5=py311h2dc5d0c_0
  - fqdn=1.5.1=pyhd8ed1ab_1
  - freetype=2.13.3=ha770c72_1
  - gflags=2.2.2=h5888daf_1005
  - glog=0.7.1=hbabe93e_0
  - gmp=6.3.0=h6a678d5_0
  - gmpy2=2.2.1=py311h5eee18b_0
  - graphite2=1.3.14=h5888daf_0
  - greenlet=3.0.3=py311hb755f60_0
  - grpcio=1.73.1=py311h7df2aa2_0
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.1.0=pyhd8ed1ab_0
  - h5py=3.14.0=nompi_py311h0b2f468_101
  - harfbuzz=11.4.5=h15599e2_0
  - hdf5=1.14.6=nompi_h2d575fe_101
  - hpack=4.0.0=pyh9f0ad1d_0
  - httpcore=1.0.9=pyh29332c3_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - hyperframe=6.0.1=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - idna=3.7=pyhd8ed1ab_0
  - importlib-metadata=7.2.1=pyha770c72_0
  - importlib_resources=6.4.0=pyhd8ed1ab_0
  - ipykernel=6.29.5=pyh3099207_0
  - ipython=9.4.0=pyhfa0c392_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - ipywidgets=8.1.7=pyhd8ed1ab_0
  - isoduration=20.11.0=pyhd8ed1ab_1
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.4=pyhd8ed1ab_0
  - joblib=1.5.1=pyhd8ed1ab_0
  - json5=0.12.0=pyhd8ed1ab_0
  - jsonpointer=3.0.0=py311h38be061_1
  - jsonschema=4.24.0=pyhd8ed1ab_0
  - jsonschema-specifications=2025.4.1=pyh29332c3_0
  - jsonschema-with-format-nongpl=4.24.0=hd8ed1ab_0
  - jupyter-lsp=2.2.5=pyhe01879c_2
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.8.1=pyh31011fe_0
  - jupyter_events=0.12.0=pyh29332c3_0
  - jupyter_server=2.16.0=pyhe01879c_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_1
  - jupyterlab=4.4.4=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - jupyterlab_server=2.27.3=pyhd8ed1ab_1
  - jupyterlab_widgets=3.0.15=pyhd8ed1ab_0
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.8=py311hd18a35c_1
  - krb5=1.21.3=h659f571_0
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.40=hf3520f5_7
  - lerc=4.0.0=h27087fc_0
  - libabseil=20250512.1=cxx17_hba17884_0
  - libaec=1.1.4=h3f801dc_0
  - libarrow=21.0.0=hb708d0b_2_cpu
  - libarrow-acero=21.0.0=h635bf11_2_cpu
  - libarrow-compute=21.0.0=hebab434_2_cpu
  - libarrow-dataset=21.0.0=h635bf11_2_cpu
  - libarrow-substrait=21.0.0=h3f74fd7_2_cpu
  - libblas=3.9.0=35_h5875eb1_mkl
  - libbrotlicommon=1.1.0=hd590300_1
  - libbrotlidec=1.1.0=hd590300_1
  - libbrotlienc=1.1.0=hd590300_1
  - libcblas=3.9.0=35_hfef963f_mkl
  - libclang-cpp18.1=18.1.8=default_hb5137d0_10
  - libclang-cpp20.1=20.1.8=default_h99862b1_1
  - libclang13=21.1.0=default_h746c552_1
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libcups=2.3.3=hb8b1518_5
  - libcurl=8.14.1=h332b0f4_0
  - libdeflate=1.24=h86f0d12_0
  - libdrm=2.4.125=hb9d3cd8_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libegl=1.7.0=ha4b6fd6_0
  - libev=4.33=hd590300_2
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.7.1=hecca717_0
  - libfabric=2.2.0=ha770c72_1
  - libfabric1=2.2.0=h47b3337_1
  - libffi=3.4.6=h2dba641_1
  - libfreetype=2.13.3=ha770c72_1
  - libfreetype6=2.13.3=h48d6fc4_1
  - libgcc=15.1.0=h767d61c_3
  - libgcc-ng=15.1.0=h69a702a_3
  - libgfortran=15.1.0=h69a702a_5
  - libgfortran-ng=15.1.0=h69a702a_5
  - libgfortran5=15.1.0=hcea5267_5
  - libgl=1.7.0=ha4b6fd6_0
  - libglib=2.84.3=hf39c6af_0
  - libglvnd=1.7.0=ha4b6fd6_0
  - libglx=1.7.0=ha4b6fd6_0
  - libgoogle-cloud=2.39.0=hdb79228_0
  - libgoogle-cloud-storage=2.39.0=hdbdcf42_0
  - libgrpc=1.73.1=h1e535eb_0
  - libhwloc=2.11.2=default_he43201b_1000
  - libiconv=1.18=h3b78370_2
  - libjpeg-turbo=3.1.0=hb9d3cd8_0
  - liblapack=3.9.0=35_h5e43f62_mkl
  - libllvm18=18.1.8=h8b73ec9_2
  - libllvm19=19.1.2=ha7bfdaf_0
  - libllvm20=20.1.8=hecd9e04_0
  - libllvm21=21.1.0=hecd9e04_0
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libnghttp2=1.67.0=had1ee68_0
  - libnl=3.11.0=hb9d3cd8_0
  - libnsl=2.0.1=hd590300_0
  - libntlm=1.8=hb9d3cd8_0
  - libopenblas=0.3.27=pthreads_hac2b453_1
  - libopengl=1.7.0=ha4b6fd6_0
  - libopentelemetry-cpp=1.21.0=hb9b0907_1
  - libopentelemetry-cpp-headers=1.21.0=ha770c72_1
  - libparquet=21.0.0=h790f06f_2_cpu
  - libpciaccess=0.18=hb9d3cd8_0
  - libpng=1.6.50=h943b412_0
  - libpq=17.6=h3675c94_1
  - libprotobuf=6.31.1=h9ef548d_1
  - libre2-11=2025.08.12=h7b12aa8_1
  - libsodium=1.0.20=h4ab18f5_0
  - libsqlite=3.50.4=h0c1763c_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.1.0=h8f9b012_3
  - libstdcxx-ng=15.1.0=h4852527_3
  - libthrift=0.22.0=h454ac66_1
  - libtiff=4.7.0=h8261f1e_6
  - libutf8proc=2.10.0=h202a827_0
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.11.0=he8b52b9_0
  - libxml2=2.13.8=h04c0eec_1
  - libxslt=1.1.39=h76b75d6_0
  - libzlib=1.3.1=h4ab18f5_1
  - llvm-openmp=21.1.0=h4922eb0_0
  - lz4-c=1.10.0=h5888daf_1
  - mako=1.3.5=pyhd8ed1ab_0
  - markdown=3.6=pyhd8ed1ab_0
  - markupsafe=2.1.5=py311h459d7ec_0
  - matplotlib=3.10.3=py311h38be061_0
  - matplotlib-base=3.10.3=py311h2b939e6_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mistune=3.1.3=pyh29332c3_0
  - mkl=2024.2.2=ha770c72_17
  - mpc=1.3.1=h5eee18b_0
  - mpfr=4.2.1=h5eee18b_0
  - mpi=1.0.1=mpich
  - mpi4py=4.1.0=py311h2a725c7_102
  - mpich=4.3.1=h1a8bee6_100
  - mpmath=1.3.0=py311h06a4308_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - mysql-common=8.3.0=h70512c7_5
  - mysql-libs=8.3.0=ha479ceb_5
  - nbclient=0.10.2=pyhd8ed1ab_0
  - nbconvert-core=7.16.6=pyh29332c3_0
  - nbformat=5.10.4=pyhd8ed1ab_1
  - ncurses=6.5=h59595ed_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - nlohmann_json=3.12.0=h3f2d84a_0
  - notebook=7.4.4=pyhd8ed1ab_0
  - notebook-shim=0.2.4=pyhd8ed1ab_1
  - numpy=1.26.4=py311h64a7726_0
  - openjpeg=2.5.3=h55fea9a_1
  - openldap=2.6.10=he970967_0
  - openssl=3.5.2=h26f9b46_0
  - optuna=3.6.1=pyhd8ed1ab_0
  - optuna-integration=3.6.0=pyhd8ed1ab_0
  - orc=2.2.0=h1bc01a4_0
  - overrides=7.7.0=pyhd8ed1ab_1
  - packaging=24.1=pyhd8ed1ab_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.4=pyhd8ed1ab_1
  - pcre2=10.45=hc749103_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.3.0=py311h3df08e7_1
  - pip=24.0=pyhd8ed1ab_0
  - pixman=0.46.2=h29eaf8c_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_2
  - platformdirs=4.3.8=pyhe01879c_0
  - prometheus-cpp=1.3.0=ha5d0236_0
  - prometheus_client=0.22.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.51=pyha770c72_0
  - protobuf=6.31.1=py311hf8041f0_0
  - psutil=7.0.0=py311h9ecbd09_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pyarrow=21.0.0=py311h38be061_0
  - pyarrow-core=21.0.0=py311h342b5a4_0_cpu
  - pycparser=2.22=pyhd8ed1ab_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyparsing=3.2.3=pyhd8ed1ab_1
  - pyside6=6.9.0=py311h9053184_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.11.9=hb806964_0_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-fastjsonschema=2.21.1=pyhd8ed1ab_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-lmdb=1.7.3=py311hc665b79_1
  - python_abi=3.11=4_cp311
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.1=py311h459d7ec_1
  - pyzmq=27.0.0=py311h7deb3e3_0
  - qhull=2020.2=h434a139_5
  - qt6-main=6.9.0=h0384650_3
  - rdma-core=58.0=h7934f7d_0
  - re2=2025.08.12=h5301d42_1
  - readline=8.2=h8228510_1
  - referencing=0.36.2=pyh29332c3_0
  - requests=2.32.3=pyhd8ed1ab_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_1
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rpds-py=0.26.0=py311hdae7d1d_0
  - s2n=1.5.23=h8e187f5_0
  - scikit-learn=1.7.1=py311hc3e1efb_0
  - scipy=1.16.0=py311h2d3ef60_0
  - send2trash=1.8.3=pyh0d859eb_1
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.2.2=h03e3b7b_0
  - sniffio=1.3.1=pyhd8ed1ab_1
  - soupsieve=2.7=pyhd8ed1ab_0
  - sqlalchemy=2.0.31=py311h331c9d8_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tbb=2021.13.0=hceb3a55_1
  - tensorboard=2.17.1=pyhd8ed1ab_0
  - tensorboard-data-server=0.7.0=py311h63ff55d_1
  - terminado=0.18.1=pyh0d859eb_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tinycss2=1.4.0=pyhd8ed1ab_0
  - tk=8.6.13=noxft_h4845f30_101
  - tomli=2.2.1=pyhd8ed1ab_1
  - tornado=6.5.1=py311h9ecbd09_0
  - tqdm=4.66.5=pyhd8ed1ab_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - types-python-dateutil=2.9.0.20250708=pyhd8ed1ab_0
  - typing-extensions=4.12.2=hd8ed1ab_0
  - typing_extensions=4.12.2=pyha770c72_0
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - tzdata=2024a=h0c530f3_0
  - ucx=1.18.1=h1369271_0
  - unicodedata2=16.0.0=py311h9ecbd09_0
  - uri-template=1.3.0=pyhd8ed1ab_1
  - urllib3=2.2.2=pyhd8ed1ab_1
  - wayland=1.23.1=h3e06ad9_0
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - webcolors=24.11.1=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - websocket-client=1.8.0=pyhd8ed1ab_1
  - werkzeug=3.0.3=pyhd8ed1ab_0
  - wheel=0.43.0=pyhd8ed1ab_1
  - widgetsnbextension=4.0.14=pyhd8ed1ab_0
  - xcb-util=0.4.1=hb711507_2
  - xcb-util-cursor=0.1.5=hb9d3cd8_0
  - xcb-util-image=0.4.0=hb711507_2
  - xcb-util-keysyms=0.4.1=hb711507_0
  - xcb-util-renderutil=0.3.10=hb711507_0
  - xcb-util-wm=0.4.2=hb711507_0
  - xkeyboard-config=2.42=h4ab18f5_0
  - xorg-kbproto=1.0.7=hb9d3cd8_1003
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxcomposite=0.4.6=hb9d3cd8_2
  - xorg-libxcursor=1.2.3=hb9d3cd8_0
  - xorg-libxdamage=1.1.6=hb9d3cd8_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.1=hb9d3cd8_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxtst=1.2.5=hb9d3cd8_3
  - xorg-libxxf86vm=1.1.6=hb9d3cd8_0
  - xorg-renderproto=0.11.1=hb9d3cd8_1003
  - xorg-xextproto=7.3.0=hb9d3cd8_1004
  - xorg-xproto=7.0.31=hb9d3cd8_1008
  - xz=5.8.1=hbcc6ac9_2
  - xz-gpl-tools=5.8.1=hbcc6ac9_2
  - xz-tools=5.8.1=hb9d3cd8_2
  - yaml=0.2.5=h7f98852_2
  - zeromq=4.3.5=h3b0a872_7
  - zipp=3.19.2=pyhd8ed1ab_0
  - zlib=1.3.1=h4ab18f5_1
  - zstandard=0.24.0=py311h4854a17_1
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - filelock==3.13.1
      - fsspec==2024.6.1
      - networkx==3.3
      - nvidia-cublas-cu12==12.9.1.4
      - nvidia-cuda-cupti-cu12==12.9.79
      - nvidia-cuda-nvrtc-cu12==12.9.86
      - nvidia-cuda-runtime-cu12==12.9.79
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.4.1.4
      - nvidia-cufile-cu12==1.14.1.1
      - nvidia-curand-cu12==10.3.10.19
      - nvidia-cusolver-cu12==11.7.5.82
      - nvidia-cusparse-cu12==12.5.10.65
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.3
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvtx-cu12==12.9.79
      - opencv-python==4.10.0.84
      - setuptools==80.9.0
      - sympy==1.13.3
      - torch==2.8.0+cu129
      - torchaudio==2.8.0+cu129
      - torchinfo==1.8.0
      - torchvision==0.23.0+cu129
      - triton==3.4.0