name: pytorch
channels:
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.14
  - numpy
  - matplotlib
  - scikit-learn
  - notebook
  - transformers
  - datasets
  - tqdm
  - torchinfo
  - pip:
      - torch --index-url https://download.pytorch.org/whl/cu130
      - torchvision --index-url https://download.pytorch.org/whl/cu130
