name: pytorch
channels:
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - mamba
  - numpy
  - matplotlib
  - transformers=4.37
  - datasets
  - scikit-learn
  - notebook
  - ipykernel
  - ipywidgets
  - widgetsnbextension
  - jupyterlab
  - jupyterlab_widgets
  - tqdm
  - torchinfo
  - optuna
  - pip:
      - torch --index-url https://download.pytorch.org/whl/cu130
      - torchvision --index-url https://download.pytorch.org/whl/cu130
